In [16]:
import pandas as pd
import numpy as np

In [17]:
dataset=pd.read_excel(r"/content/product_cost_prediction.csv")

In [18]:
dataset

,productname,uom,qty,rate,amount,taxableamt,cgstrate,cgstamt,sgstrate,sgstamt,total,originalrate
0,671-LT,Nos,14,155.0000,2170.0000,2170.0000,9.0,195.30000,9.0,195.30000,2560.6,155.0000
1,673-HLA,Nos,1,155.0000,155.0000,155.0000,9.0,13.95000,9.0,13.95000,182.9,155.0000
2,GIALLO GRENE,Nos,3,230.0000,690.0000,690.0000,9.0,62.10000,9.0,62.10000,814.2,230.0000
3,CANYON BROWN,Nos,28,475.0000,13300.0000,13300.0000,9.0,1197.00000,9.0,1197.00000,15694.0,475.0000
4,HERIC GRAFITO-LT,Nos,2,255.0000,510.0000,510.0000,9.0,45.90000,9.0,45.90000,601.8,255.0000
...,...,...,...,...,...,...,...,...,...,...,...,...
1127,MAGNA BAINCO-MN1,NOS,1,589.8305,589.8305,589.8305,9.0,53.08475,9.0,53.08475,696.0,696.0000
1128,SIFON BAINCO,NOS,6,617.3729,3704.2370,3704.2370,9.0,333.38130,9.0,333.38130,4371.0,728.5000
1129,HERICAN TUSK,NOS,19,919.4916,17470.3400,17470.3400,9.0,1572.33000,9.0,1572.33000,20615.0,919.4916
1130,MYK TIL;E ADHESIVE 305,NOS,4,254.2372,1016.9490,1016.9490,9.0,91.52540,9.0,91.52540,1200.0,300.0000
1131,MYK TILE ADHESIVE 290,NOS,4,593.2203,2372.8810,2372.8810,9.0,213.55930,9.0,213.55930,2800.0,700.0000

In [19]:
dataset.describe()

,qty,rate,amount,taxableamt,cgstrate,cgstamt,sgstrate,sgstamt,total,originalrate
count,1132.000000,1132.000000,1132.000000,1132.000000,1132.000000,1132.000000,1132.000000,1132.000000,1132.000000,1132.000000
mean,8.898410,842.187548,5658.961670,5406.067598,9.045495,483.558579,9.045495,483.558579,6370.710329,864.544643
std,11.390866,921.384641,7936.479524,7872.115634,0.868399,705.039318,0.868399,705.039318,9260.075430,962.922079
min,1.000000,33.000000,66.000000,66.000000,0.000000,0.000000,0.000000,0.000000,77.880000,33.000000
25%,1.000000,325.000000,1147.880750,920.000000,9.000000,82.750000,9.000000,82.750000,1085.600000,333.750000
50%,5.000000,602.000000,2520.000000,2288.779650,9.000000,205.520350,9.000000,205.520350,2710.460000,605.000000
75%,11.000000,961.250000,6602.542250,6076.250000,9.000000,541.125000,9.000000,541.125000,7180.890000,991.250000
max,109.000000,7625.000000,65861.870000,65861.870000,14.000000,5927.570000,14.000000,5927.570000,77717.010000,7625.000000

In [20]:
dataset.shape

(1132, 12)

In [21]:
dataset["amount"]

0        2170.0000
1         155.0000
2         690.0000
3       13300.0000
4         510.0000
           ...
1127      589.8305
1128     3704.2370
1129    17470.3400
1130     1016.9490
1131     2372.8810
Name: amount, Length: 1132, dtype: float64

In [22]:
dataset["amount"].count

<bound method Series.count of 0        2170.0000
1         155.0000
2         690.0000
3       13300.0000
4         510.0000
           ...
1127      589.8305
1128     3704.2370
1129    17470.3400
1130     1016.9490
1131     2372.8810
Name: amount, Length: 1132, dtype: float64>

In [23]:
dataset["amount"].var

<bound method NDFrame._add_numeric_operations.<locals>.var of 0        2170.0000
1         155.0000
2         690.0000
3       13300.0000
4         510.0000
           ...
1127      589.8305
1128     3704.2370
1129    17470.3400
1130     1016.9490
1131     2372.8810
Name: amount, Length: 1132, dtype: float64>

In [24]:
dataset["uom"].unique

<bound method Series.unique of 0       Nos
1       Nos
2       Nos
3       Nos
4       Nos
       ...
1127    NOS
1128    NOS
1129    NOS
1130    NOS
1131    NOS
Name: uom, Length: 1132, dtype: object>

In [25]:
dataset["uom"].head()

0    Nos
1    Nos
2    Nos
3    Nos
4    Nos
Name: uom, dtype: object

In [26]:
dataset["uom"].tail()

1127    NOS
1128    NOS
1129    NOS
1130    NOS
1131    NOS
Name: uom, dtype: object

In [27]:
a=[]
for x in dataset["rate"]:
    x1=x+10
    a.append(x1)

In [28]:
dataset["new rate"]=a
dataset

,productname,uom,qty,rate,amount,taxableamt,cgstrate,cgstamt,sgstrate,sgstamt,total,originalrate,new rate
0,671-LT,Nos,14,155.0000,2170.0000,2170.0000,9.0,195.30000,9.0,195.30000,2560.6,155.0000,165.0000
1,673-HLA,Nos,1,155.0000,155.0000,155.0000,9.0,13.95000,9.0,13.95000,182.9,155.0000,165.0000
2,GIALLO GRENE,Nos,3,230.0000,690.0000,690.0000,9.0,62.10000,9.0,62.10000,814.2,230.0000,240.0000
3,CANYON BROWN,Nos,28,475.0000,13300.0000,13300.0000,9.0,1197.00000,9.0,1197.00000,15694.0,475.0000,485.0000
4,HERIC GRAFITO-LT,Nos,2,255.0000,510.0000,510.0000,9.0,45.90000,9.0,45.90000,601.8,255.0000,265.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127,MAGNA BAINCO-MN1,NOS,1,589.8305,589.8305,589.8305,9.0,53.08475,9.0,53.08475,696.0,696.0000,599.8305
1128,SIFON BAINCO,NOS,6,617.3729,3704.2370,3704.2370,9.0,333.38130,9.0,333.38130,4371.0,728.5000,627.3729
1129,HERICAN TUSK,NOS,19,919.4916,17470.3400,17470.3400,9.0,1572.33000,9.0,1572.33000,20615.0,919.4916,929.4916
1130,MYK TIL;E ADHESIVE 305,NOS,4,254.2372,1016.9490,1016.9490,9.0,91.52540,9.0,91.52540,1200.0,300.0000,264.2372
1131,MYK TILE ADHESIVE 290,NOS,4,593.2203,2372.8810,2372.8810,9.0,213.55930,9.0,213.55930,2800.0,700.0000,603.2203

In [29]:
dataset.insert(4,"newr ",a)
dataset

,productname,uom,qty,rate,newr,amount,taxableamt,cgstrate,cgstamt,sgstrate,sgstamt,total,originalrate,new rate
0,671-LT,Nos,14,155.0000,165.0000,2170.0000,2170.0000,9.0,195.30000,9.0,195.30000,2560.6,155.0000,165.0000
1,673-HLA,Nos,1,155.0000,165.0000,155.0000,155.0000,9.0,13.95000,9.0,13.95000,182.9,155.0000,165.0000
2,GIALLO GRENE,Nos,3,230.0000,240.0000,690.0000,690.0000,9.0,62.10000,9.0,62.10000,814.2,230.0000,240.0000
3,CANYON BROWN,Nos,28,475.0000,485.0000,13300.0000,13300.0000,9.0,1197.00000,9.0,1197.00000,15694.0,475.0000,485.0000
4,HERIC GRAFITO-LT,Nos,2,255.0000,265.0000,510.0000,510.0000,9.0,45.90000,9.0,45.90000,601.8,255.0000,265.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127,MAGNA BAINCO-MN1,NOS,1,589.8305,599.8305,589.8305,589.8305,9.0,53.08475,9.0,53.08475,696.0,696.0000,599.8305
1128,SIFON BAINCO,NOS,6,617.3729,627.3729,3704.2370,3704.2370,9.0,333.38130,9.0,333.38130,4371.0,728.5000,627.3729
1129,HERICAN TUSK,NOS,19,919.4916,929.4916,17470.3400,17470.3400,9.0,1572.33000,9.0,1572.33000,20615.0,919.4916,929.4916
1130,MYK TIL;E ADHESIVE 305,NOS,4,254.2372,264.2372,1016.9490,1016.9490,9.0,91.52540,9.0,91.52540,1200.0,300.0000,264.2372
1131,MYK TILE ADHESIVE 290,NOS,4,593.2203,603.2203,2372.8810,2372.8810,9.0,213.55930,9.0,213.55930,2800.0,700.0000,603.2203

In [30]:
dataset["new rate"].nunique()

360

In [31]:
a=[]
for x in dataset["new rate"]:
    if x in range(0,100):
        a.append("low rate")
    elif x in range(100,300):
        a.append("medium rate")
    else:
        a.append("high rate")

In [32]:
a

['medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'low rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'low rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'low rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'low rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'low rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'medium rate',
 'low rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'high rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'medium rate',
 'medium rate',
 'medium rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'low rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 'high rate',
 ...]

In [33]:
dataset.insert(5,"rate range",a)
dataset

,productname,uom,qty,rate,newr,rate range,amount,taxableamt,cgstrate,cgstamt,sgstrate,sgstamt,total,originalrate,new rate
0,671-LT,Nos,14,155.0000,165.0000,medium rate,2170.0000,2170.0000,9.0,195.30000,9.0,195.30000,2560.6,155.0000,165.0000
1,673-HLA,Nos,1,155.0000,165.0000,medium rate,155.0000,155.0000,9.0,13.95000,9.0,13.95000,182.9,155.0000,165.0000
2,GIALLO GRENE,Nos,3,230.0000,240.0000,medium rate,690.0000,690.0000,9.0,62.10000,9.0,62.10000,814.2,230.0000,240.0000
3,CANYON BROWN,Nos,28,475.0000,485.0000,high rate,13300.0000,13300.0000,9.0,1197.00000,9.0,1197.00000,15694.0,475.0000,485.0000
4,HERIC GRAFITO-LT,Nos,2,255.0000,265.0000,medium rate,510.0000,510.0000,9.0,45.90000,9.0,45.90000,601.8,255.0000,265.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127,MAGNA BAINCO-MN1,NOS,1,589.8305,599.8305,high rate,589.8305,589.8305,9.0,53.08475,9.0,53.08475,696.0,696.0000,599.8305
1128,SIFON BAINCO,NOS,6,617.3729,627.3729,high rate,3704.2370,3704.2370,9.0,333.38130,9.0,333.38130,4371.0,728.5000,627.3729
1129,HERICAN TUSK,NOS,19,919.4916,929.4916,high rate,17470.3400,17470.3400,9.0,1572.33000,9.0,1572.33000,20615.0,919.4916,929.4916
1130,MYK TIL;E ADHESIVE 305,NOS,4,254.2372,264.2372,high rate,1016.9490,1016.9490,9.0,91.52540,9.0,91.52540,1200.0,300.0000,264.2372
1131,MYK TILE ADHESIVE 290,NOS,4,593.2203,603.2203,high rate,2372.8810,2372.8810,9.0,213.55930,9.0,213.55930,2800.0,700.0000,603.2203

In [34]:
dataset["new rate"].max()

7635.0